### PR TITLE
TableDataEditor.js Updates

### PR DESCRIPTION
**Pull request by jattwood**
- Changed allowable number of columns from 12 to 24

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @jattwood 

This package is based on some code we had across different projects. I wasn't aware if this limitation in the code when converting our code to a package, and only found out about it recently. I had a chat about this with a coworker just last week, and our conclusion was to remove this entirely. I just haven't gotten around to updating the package yet.

The UI may not work that great as the table gets more columns, but this may among other things depend on the user's window width, so it's hard to know exactly at which column count should be the limit. And it's still possible to edit the table even though the user experience takes a hit as the column count grows. So let's just remove this limit entirely. Can you update your PR to reflect this?

**Comment by jattwood** [comment]
Ok Done (I think). I also updated the V1 branch as well. Hope I did that correctly. Had some git issues earlier, but I think it should be ok. Still working off 11 currently but hope to migrate to 13 over the next few weeks.

Thanks!

**Comment by abjerner** [comment]
Normally we can just cherry pick changes from one branch to another, but from a quick glance on GitHub, both your PRs look spot on 👍 

I look into pushing a new release for either branch when I can find some time 😉

**Comment by jattwood** [comment]
Ok great - much appreciated.

**Comment by jattwood** [comment]
Any chance you would be able to merge and release this PR? Need to launch a site in the next week that's using the tables and it would be great to include this. Thanks!

**Comment by abjerner** [comment]
Thanks a lot 👍

**Pull request merged**
